SELECT e1.ID, e3.FISH_NAME, e1.LENGTH
FROM FISH_INFO AS e1
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS e2
ON e1.FISH_TYPE = e2.FISH_TYPE AND e1.LENGTH = e2.MAX_LENGTH
JOIN FISH_NAME_INFO AS e3
ON e1.FISH_TYPE = e3.FISH_TYPE;
