SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) A
    ON RI.FOOD_TYPE = A.FOOD_TYPE
    AND RI.FAVORITES = A.FAVORITES
ORDER BY FOOD_TYPE DESC
